[project]
name = "gdtw"
version = "1.1.3"
requires-python = ">=3.7"
authors = [
	{name = "Dave Deriso", email = "dderiso@alumni.stanford.edu"},
]

[build-system]
requires = [
    "setuptools",
    "numpy>=1.20.0",
]
build-backend = "setuptools.build_meta"
