name: Build & Deploy OSX Wheel

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: dderiso/gdtw

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine numpy

    - name: Build wheel
      run: |
        python setup.py bdist_wheel
      env:
        PYTHONPATH: ${{ env.pythonLocation }}

    - name: Publish Wheel
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 -m pip install twine
        ls -al dist/
        latest_wheel=$(ls -t dist/*.whl | head -1)
        echo $latest_wheel
        python3 -m twine upload $latest_wheel
